[package]
name = "vector-extensions"
version = "0.23.3"
edition = "2021"
readme = "README.md"
publish = false
default-run = "vector"

[[bin]]
path = "src/main.rs"
name = "vector"

[features]
default = ["topsql", "vm-import", "aws-s3-upload-file", "filename"]

topsql = ["dep:topsql"]
vm-import = ["dep:vm-import"]
aws-s3-upload-file = ["dep:aws-s3-upload-file"]
filename = ["dep:filename"]

[dependencies]
vector = { git = "https://github.com/vectordotdev/vector", tag = "v0.23.3", default-features = false }

# Extensions
topsql = { path = "extensions/topsql", optional = true }
vm-import = { path = "extensions/vm-import", optional = true }
aws-s3-upload-file = { path = "extensions/aws-s3-upload-file", optional = true }
filename = { path = "extensions/filename", optional = true }

[dev-dependencies]
hyper = { version = "0.14.20", default-features = false, features = ["client", "runtime", "http1", "http2", "server", "stream"] }
tokio = { version = "1.20.1", default-features = false, features = ["full"] }
url = "2.3.1"
regex = "1.6.0"
lazy_static = "1.4.0"

[workspace]
members = [
    "extensions/common",
    "extensions/topsql",
    "extensions/vm-import",
    "extensions/aws-s3-upload-file",
    "extensions/filename",
]

[patch.'https://github.com/vectordotdev/vector']
vector = { git = "https://github.com/zhongzc/vector", branch = "extend-0.23" }
vector_core = { git = "https://github.com/zhongzc/vector", branch = "extend-0.23" }

[patch.crates-io]
# Removes dependency on `time` v0.1
# https://github.com/chronotope/chrono/pull/578
chrono = { git = "https://github.com/vectordotdev/chrono.git", branch = "no-default-time" }
# The upgrade for `tokio-util` >= 0.6.9 is blocked on https://github.com/vectordotdev/vector/issues/11257.
tokio-util = { git = "https://github.com/vectordotdev/tokio", version = "0.7", rev = "3aa231cf6f33f74ca29077163879f0de9a207ad8" }
