[package]
name = "vector-extensions"
version = "0.23.3"
edition = "2021"
readme = "README.md"
publish = false
default-run = "vector"

[[bin]]
path = "src/main.rs"
name = "vector"

[features]
default = ["topsql", "vm-import"]

topsql = ["dep:topsql"]
vm-import = ["dep:vm-import"]

[dependencies]
vector = { git = "https://github.com/vectordotdev/vector", tag = "v0.23.3", default-features = false }

# Extensions
topsql = { path = "extensions/topsql", optional = true }
vm-import = { path = "extensions/vm-import", optional = true }

[workspace]
members = [
    "extensions/topsql",
    "extensions/vm-import",
]

[patch.'https://github.com/vectordotdev/vector']
vector = { git = "https://github.com/zhongzc/vector", branch = "extend" }
vector_core = { git = "https://github.com/zhongzc/vector", branch = "extend" }
