[package]
name = "vector-extensions"
version = "0.24.0"
edition = "2021"
readme = "README.md"
publish = false
default-run = "vector"
rust-version = "1.62.0"

[[bin]]
path = "src/main.rs"
name = "vector"

[features]
default = ["topsql", "vm-import"]

topsql = ["dep:topsql"]
vm-import = ["dep:vm-import"]

[dependencies]
vector = { git = "https://github.com/tidbcloud/vector", default-features = false }

# Extensions
topsql = { path = "extensions/topsql", optional = true }
vm-import = { path = "extensions/vm-import", optional = true }

[workspace]
members = [
    "extensions/topsql",
    "extensions/vm-import",
]

[patch.'https://github.com/tidbcloud/vector']
vector = { git = "https://github.com/zhongzc/vector", branch = "extendability" }
vector_core = { git = "https://github.com/zhongzc/vector", branch = "extendability" }
