[package]
name = "common"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
chrono = { version = "0.4.19", default-features = false, features = ["clock", "serde"] }
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.81", default-features = false, features = ["std", "raw_value"] }
tracing = { version = "0.1.34", default-features = false }
vector-core = { git = "https://github.com/vectordotdev/vector", tag = "v0.31.0", default-features = false, features = ["vrl"] }
